services:
  telegrambot:
    image: ejercicio-telegrambot
    build:
      context: ./telegrambot
    container_name: ejercicio-telegrambot
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - TB_TOKEN=${TB_TOKEN}
      - TB_AUTORIZADOS=${TB_AUTORIZADOS}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USR=${MQTT_USR}
      - MQTT_PASS=${MQTT_PASS}
      - TOPICO=${TOPICO}
      - PICO_DEVICE_ID=${PICO_DEVICE_ID}
